;;; corfu-candidate-overlay-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from corfu-candidate-overlay.el

(autoload 'corfu-candidate-overlay-complete-at-point "corfu-candidate-overlay" "\
Insert the first completion candidate shown in the overlay." t)
(defvar corfu-candidate-overlay-mode nil "\
Non-nil if Corfu-Candidate-Overlay mode is enabled.
See the `corfu-candidate-overlay-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `corfu-candidate-overlay-mode'.")
(custom-autoload 'corfu-candidate-overlay-mode "corfu-candidate-overlay" nil)
(autoload 'corfu-candidate-overlay-mode "corfu-candidate-overlay" "\
Show first candidate in an overlay while typing.

This is a global minor mode.  If called interactively, toggle the
`Corfu-Candidate-Overlay mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-candidate-overlay-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-candidate-overlay" '("corfu-candidate-overlay-"))

;;; End of scraped data

(provide 'corfu-candidate-overlay-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; corfu-candidate-overlay-autoloads.el ends here
